### ISSUE TITLE
Error when creating and updating 'checkupdate_*.tmp' file

### ISSUE THREAD

**Issue by damianperera** [axelhahn/pimped-apache-status#1]
PHP throws an error when creating and updating the **checkupdate_*.tmp** file. This happens since the _inc_functions.php_ file is attempting to R/W this file in the systems default tmp folder (usually _/tmp/_) which is not accessible to PHP in hosts with _safe_mode_ and _open_basedir_ enabled.

**Comment by axelhahn** [comment]
Thanks for this advice wih _save_mode_ and _open_basedir_ option!
The update via web frontend is not ready in version 2 (which is still beta). 
I will put it to version 1.x too.

**Comment by axelhahn** [comment]
@damianperera I was a bit fast. While testing I saw that webroot / approot itself is not a good idea. I will add a subdir i.e. "tmp" and define that [approot]/tmp must be writable. The idea behind is: if I use Puppet/ Chef/ ... and I install the tool as root then all files can be non writable for the webservice ... excluding specific, named folders. So far in version 1.x only the _./config/_ directory must be writable: https://www.axel-hahn.de/docs/apachestatus/get_started.htm#Permissions; in version 2 below _./vendor/_ too. Just wanna say that I will make a small change after the merge :-)

**Comment by damianperera** [comment]
@axelhahn sounds good, adding a subdir within the document root would definitely be better than using the system's tmp folder or the document root 👍

**Comment by axelhahn** [comment]
@damianperera I added a config variable "tmpdir". It has the default "tmp" that points to [approot]/tmp. In the user config it is allowed to override it or use system temp dir. This seems to be the variant with the most control. The temp directroy is used for the version check (where you detected it) and in the updater.
Version 1.x + documentation was updated too.
