### ISSUE TITLE
Downloaded vendor requests get 404 if running in root directory / subdomain

### ISSUE THREAD

**Issue by toubsen** [axelhahn/pimped-apache-status#10]
When downloading vendor libraries (to fetch from the local server), it will work fine across all pages, if pimped-apache-status is running in a sub-directory. Example:
```
# Example base installation URL
https://foo.bar.com/status/

# Example URL for admin:
https://foo.bar.com/status/admin/?&action=settings

# Example GET request to vendor resource 
https://foo.bar.com/status/vendor//jquery/3.3.1/jquery.min.js
``` 
When running pimped-apache-status on a subdomain, vendor downloads will not work inside "sub-folders", e.g. in admin settings and throw a 404. Example of this setup:
```
https://status.foo.com/

# Example URL for admin:
https://status.foo.com/admin/?&action=settings

# GET request to vendor resource:
https://status.foo.com/admin/vendor//jquery/3.3.1/jquery.min.js
``` 

Looks like, the URL creation for resources will not properly strip the first leading directory, even if needed so.

**Comment by toubsen** [comment]
Possible work-around: Set "selfurl" to "https://status.foo.com/" - this will work, but only with trailing slash, the create URLs as following: "https://status.foo.com//admin/?&action=settings".

When removing the trailing slash on "selfurl", thus creating URLs like "https://status.foo.com/admin/?&action=settings" (without double slash), resource fetching will fail again.

**Comment by axelhahn** [comment]
Hi toubsen
thanks for the report and all the given examples. There is a class (cdnorlocal) that should handle local ressources or get it from a CDN. I will check the installation directly in webroot and will send you feedback soon.
Axel

**Comment by axelhahn** [comment]
Hi toubson,
I found it ... and made a commit into a branch. The mistake was in the initialisation of the cdnorlocal class. For requests to the admin area the base url was initialised in a wrong way. The detection for '/admin/' in the url was too lazy. 

see inc_functions.php in the commit
https://github.com/axelhahn/pimped-apache-status/commit/02b67ca69556008329cb43efbca1bf49da32229c

I will check the reason of your other issue https://github.com/axelhahn/pimped-apache-status/issues/9 before merging it.

Kind regards,
Axel

**Comment by axelhahn** [comment]
Hi toubsen,

I fixed it and merged into master. To perform the build-in web updater with the broken installation I suggest to empty the vendor directory temporarely.

I would be happy to get your feedback if it works with the 2 fixes.

Regards,
Axel

**Comment by toubsen** [comment]
Hi Alex,

also tested this with a fresh clean install and on upgrade (with the inplace auto-updater). Works fine now for both scenarios.

Thanks a lot for the quick support + fixes! :-)

Kind regards
Tobias
