### ISSUE TITLE
Exclude request from collection server.

### ISSUE THREAD

**Issue by paulzakk** [axelhahn/pimped-apache-status#13]
The server-status request on the collection server is also aggregated.
I wish there was an option to exclude requests from the collection server from all aggregations.
For example, if the client is a collection server, it will be excluded from the aggregate, and information will not appear in all tables.

**Comment by paulzakk** [comment]
Pimped Apache Status Server's / server-status / request can be seen in all tables (tables in Perfomance checks, tables in All requests).
For example, if the IP of the Pimped Apache Status Server is 1.1.1.1, if the client's IP is 1.1.1.1, it would be nice to have the ability to filter it out of the table.

**Comment by axelhahn** [comment]
Ah OK, I understood. You don't talk about removing a server that should not be asked for its server status. You need a filter from IP (column "Client") combined with a requested path (column "Request") in the resultset. 
The "/server-status" request can be redefined like an alias to something else. In theory each server can define its own alias. I think 
(1) it must be an option as boolean in the settings... 
(2) From the server settings I parse the values of all urls to exclude each serverspecific path
I will have a look what else I should add in an exlude filter list.

**Comment by paulzakk** [comment]
Right! I think the request (/ server-status) from the Pimped Apache Status Server does not need to be visible. And I think this request should not be counted.
This feature is very good when added.

**Comment by axelhahn** [comment]
Hi, I published an update. I already had a filter mechanism to create my views (extract the active requests and remove inactive or waitning slots) - I made a change to customize it by config too. With the "hideRows" value you can remove lines where a column contains a given value (i.e. column Client contains the ip address of the monitoring system) or matches a regex (i.e. column Request contains a request). In the docs I added a section for a few tricks:
https://www.axel-hahn.de/docs/apachestatus/howto.htm
From here you can copy and paste the example snippets.
I hope it helps :-)
