### ISSUE TITLE
user_config file not working

### ISSUE THREAD

**Issue by nasersobhan** [axelhahn/pimped-apache-status#15]
Hi, 
I am trying it set a password to secure it but it's not just working I tried normal text (password) and MD5 it but still not accepting my password so I have to set it false (I mean password). then it's public what should I do?

**Comment by axelhahn** [comment]
Hi,
in the config you need to store the password as md5. You can find it out on command line too:
```
$ php -r "echo md5('hello');"
5d41402abc4b2a76b9719d911017c592
```
(This "hello" is just an example - use something password like, OK?!).
This md5 output of "hello" must be set next to a user:
```
{
    "auth": {
        "user": "monitoradmin",
        "password": "5d41402abc4b2a76b9719d911017c592"
    }
}
```
Then you need to login with user "monitoradmin" and the password "hello".

I don't know your environment so I give more general hints. 
Have look to the docs regarding the hardening: https://www.axel-hahn.de/docs/apachestatus/harden.htm
For a company the monitoring server can/ should be placed inside the network without public access (OK, this is not possible with a shared hosting). Even with with a disabled password: you also can restrict the acces by "normal" httpd access rules in httpd.conf, i.e. if you need to to set up more than 1 user or set an ip restriction.
Using an SSL certificate is a must that no sniffer can read transmitted user data or password (i.e. Lets's encrypt).

I hope that it helps.

Axel

**Comment by nasersobhan** [comment]
I tried it  but still not working should I change the user too, I mean is it necessary ?

**Comment by nasersobhan** [comment]
nop, I tried your Json code too.
`   "auth": {
        "user": "monitoradmin",
        "password": "5d41402abc4b2a76b9719d911017c592"
    },`
still not accepting it, 
I am using it under domain.com/sub/sub in CentOS 7, Apache 2.4 with FastCGI. if it helps and I updated yesterday to the latest version 2.02 i though it will be solved with new version - (I had the same problem with pervious version)

**Comment by axelhahn** [comment]
Hi, I have environments with mod_php only but not with FastCGI - there should be the problem: I never tested it so far. I need to build a setup first to verify it.
(1) The fastest way for you to get it run is: use "auth": false and setup the protection with apache config (Basic Authentication, IP restriction)
(2) If you want to help me and debug it... the authentication uses $_SERVER['PHP_AUTH_USER'] and $_SERVER['PHP_AUTH_PW'] - it is handled in the inc_functions.php in the function checkAuth(). It must have something to do with these both $_SERVER variables.

**Comment by nasersobhan** [comment]
oh Okay I think it might be the cloudflare thing too, I am using cloudflare and it changes some of header vars. I will check it and I will let you know. 
thank you. great job by the way.

**Comment by axelhahn** [comment]
Hi,
I think its done: 
- I updated the logon - and switched from BasicAuth to a login form and store it in a session. This works with FastCgi too. Additionally there is a real logout now.
- there was an error in the initial setup after uncompressing the first time. The username was not stored.
If you update to tha latest version (you can use the built in web updater) ... can you confirm that it works for you?! Or do you see something else?
Axel

**Comment by nasersobhan** [comment]
thank you, i used htaccess to secure it at the meantime.
