### ISSUE TITLE
Record history

### ISSUE THREAD

**Issue by qmnty** [axelhahn/pimped-apache-status#22]
Is possible to record realtime data to database? So we can see the history of apache monitoring data in future, sort by date/time.

Thank you

**Comment by axelhahn** [comment]
Hi qmnty,

not really ... This tool fetches real time data of the requested server(s) of running processes that are in no log yet.

The browser gui renders them - or you can use the API to get raw data as JSON, CSV, XML. See https://www.axel-hahn.de/docs/apachestatus/api.htm. To find an url with raw data you also can use the export below each table in the web gui.

To store a view in a database you need to take the api output of every n seconds and put it to a database. Maybe you explain your idea what do you want to store. You have all finished requests in the access.log and you can generate a web statistics with them (i.e. using Matomo).

Regards,
Axel

**Comment by ThomasCr** [comment]
but maybe the access.log will not hold the data from all virtual hosts of apache and also not the details about renderiing time and so on.

I understand what your script is doing, but I also understand, that it would be nice to record this data to track down apache response times and so on.

But I think, that this script would be not the right place to do so. It should be recorded from apache itself - like the data from the status mod.

**Comment by axelhahn** [comment]
Hi Thomas,

thanks for the additional lines.

In our institute we have 50..100 webservers - those I group by application or by zone or department ... in different ways. Some servers are listed in different groups. With a single web request I never fetch all servers. 

What I could do is adding an API parameter for output of a dump format that can reimported by the web gui (with a new url parameter or handled by a POST request).

With a wrapper it would be possible to make an api request. The wrapper needs to store the requested group or servername next to the resultset and timestamp.
A Cronkob starts the wrapper every N minutes...

Additionally an interface is neeeded to present the dates / times/ data. With a click you open the pimped apache status with the import parameter to present the selected data - i.e. in an iframe.

But I have no idea for a general solution that could fit all constellations having all my current servers and groups in my mind.

regards,
Axel

**Comment by axelhahn** [comment]
Closing issue after 1 year+ without further inputs.
