### ISSUE TITLE
$sSelfURL should be set by default to a URL not local path

### ISSUE THREAD

**Issue by ThomasCr** [axelhahn/pimped-apache-status#24]
After extract te setup and open the webpage, I found that many things like css and js files are loaded from /var/www/.... local path, which are for sure are not accessible from internet.

After some search I found, that this value is loaded from the environment var DOCUMENT_ROOT which is a bad idea.

https://github.com/axelhahn/pimped-apache-status/blob/5a2037c10df489b27f4efabfd2c28bfe41023e48/inc_config.php#L55

is always the best idea, to use relative paths in your template, so that you dont need such a construct with fixed paths.

https://github.com/axelhahn/pimped-apache-status/blob/5a2037c10df489b27f4efabfd2c28bfe41023e48/classes/html.tpl.php#L12
https://github.com/axelhahn/pimped-apache-status/blob/5a2037c10df489b27f4efabfd2c28bfe41023e48/classes/html.tpl.php#L13
https://github.com/axelhahn/pimped-apache-status/blob/5a2037c10df489b27f4efabfd2c28bfe41023e48/templates/default/out_html.php#L14

There you should just use the relative paths.

**Comment by ThomasCr** [comment]
urg... ok, all generated links suffer from the same problem.
I also found now, that it is possible to set selfurl - but I say, that It should not be need.

It would be better to read SCRIPT_URI or REDIRECT_SCRIPT_URL env vars as default address.

**Comment by axelhahn** [comment]
Hi Thomas,

thanks for your report. But help me to understand what problem you try to solve.

A) The "normal" constellation is: that the archive is extracted in or below webroot. Then it will find the base directory of the app relative to document root. 
B) If you extract it "anywhere" and use an alias - the you need to set selfurl to point to the alias.

What I need to do to reproduce your constellation? Where did you extract it - and where is the webroot?

kind regards,
Axel

**Comment by ThomasCr** [comment]
Yes, it was used with an alias in Apache. But as I pointed out, it could be more easy to make use of the vars SCRIPT_URI/REDIRECT_SCRIPT_URI so nobody need to manually set selfurl.

**Comment by axelhahn** [comment]
The variable `$sSelfURL` points to the application base url - not the current url of the page. 
The pages returning html code in the webui are directly in that approot url and setting pages in subdir _/admin_. I could set the application root by a hartcoded replacement od the directory name _/admin_. To prevent hartcoded replacements was the former reason to create a custom config variable. On the other hand: there is just this constellation only to handle ... I will update it in the next version and remove the config var.

`$sSelfURL=preg_replace('#\/admin$#', '', dirname($_SERVER['SCRIPT_NAME']));`

**Comment by axelhahn** [comment]
It is done with https://github.com/axelhahn/pimped-apache-status/commit/883c8253aefce3708e2e689c85cdb61d0e550590#diff-ceefa11783c184687f67cca61c026a1e1eca03cfcb4f02a64627fb9083044690
