### ISSUE TITLE
After Upgrade unable to migrate configuration

### ISSUE THREAD

**Issue by cbrassel** [axelhahn/pimped-apache-status#31]
Hy after upgrading from 1.x to the latest I was unable to migrate te configuration with the following issue:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'confighandler' not found in /var/www/apache-status/upgrade.php:10\nStack trace:\n#0 {main}\n  thrown in /var/www/apache-status/upgrade.php on line 10',

The php file exists and is readable:
/var/www/apache-status # ls -la classes/confighandler.class.php
-rw-r--r-- 1 www-data www-data 8753 Aug 16 17:17 classes/confighandler.class.php

Any suggestion ?
Thanks
Regards
C. Brassel

**Comment by axelhahn** [comment]
Hi C.Brassel,
Thanks for your report!

I was able to verify it. It means: somewhen I changed the namespace in the confighandler class - and forgot to update the upgrade script :-/

Fast slolution: you can edit the _upgrade.php_ - line 10 - and add namespace "axelhahn\":
OLD: `$oCfg = new confighandler("internal-env");`
NEW: `$oCfg = new axelhahn\confighandler("internal-env");`
Then the class will be loaded. 

The _upgrade.php_ is needed once to convert the config of version 1 - then never again.
I will add the fix above in the next update.

Regards,
Axel

**Comment by cbrassel** [comment]
yes ! great ! thank you that did the trick !

By the way .. great piece of software, glad you made it !

Regard's
Claude
