### ISSUE TITLE
bad slot stats with apache 2.4 (event)

### ISSUE THREAD

**Issue by pavelriha** [axelhahn/pimped-apache-status#36]
I configured several servers with apache 2.2, and works without problem
then addes one with apache 2.4 ( Multi processing module: event ) and there is some problem with reporting and than in visualisation

250 Slots
Active: 12
Idle: 338
Unused: -100 

apache config
<IfModule mpm_event_module>
    StartServers        1
    MinSpareThreads     25
    MaxSpareThreads     75
    ThreadsPerChild     25
    MaxRequestWorkers   250
    MaxConnectionsPerChild  10000
</IfModule>

**Comment by axelhahn** [comment]
Hello pavelriha,
thanks for reporting this issue.
I have Apache 2.4 for several years in our networks. As MPM worker ans MPM event. 
On MPM worker the count of "slots" is the max. count of workers. On MPM event the count of max processes x count of threads per child. It is not a known issue for me. Can you send me the response of the server-status page (html output) to verify it? Feel free to to replace the hostnames and requests. 
Thanks!
Axel

**Comment by pavelriha** [comment]
Hi axelhahn,
it's a bit weird, I have two apache2.4event servers and both had this issue before.
But now I logged into Pimped and one of them (hosting04) is OK now
Slots: 250; Active: 10, Idle: 140; Unused: 100

but the second (azet) is still bad:
Slots: 250; Active: 35, Idle: 265; Unused: -50

I'm attaching header of both status pages

[apache_stats.zip](https://github.com/axelhahn/pimped-apache-status/files/11507910/apache_stats.zip)

**Comment by axelhahn** [comment]
Thanks for the status pages. 
What I see that there are no details of the processed requests of each slot in it.
You need to enable `ExtendedStatus On` too. 
https://www.axel-hahn.de/docs/apachestatus/get_started.htm#Onmonitoredsystems
I think I added a warning if this option is disabled. I will check with your output files.

**Comment by pavelriha** [comment]
ExtendedStatus is enabled,  I manually deleted it from attach

**Comment by axelhahn** [comment]
I saw that there is a gap in the counters for total/ free/ used/ unused slots. Partly I used the scoreboard and partly the requests (coming with extended status on) what is a but stupid. I will clean it up and use the scoreboard chars only (the area with _ . W R and other letters).
It comes in the next version (currently I update some other classes and libs).

**Comment by axelhahn** [comment]
Hello pavelriha,
The branch for the new version was merged. You should get an update info and can follow the assistent to upgrade. Or run `git pull` if you used git.
Didi it solve the reported problem?
Axel

**Comment by pavelriha** [comment]
both server looks correct now, no negative numbers
great, thak you
