### ISSUE TITLE
PHP error DivisionByZeroError

### ISSUE THREAD

**Issue by azurit** [axelhahn/pimped-apache-status#38]
Hi,

i did only this:
 - unpacked it
 - opened in browser
 - set the password

Now it is showing this PHP error:
```
PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /home/.../apache.....sk/classes/datarenderer.class.php:1454
Stack trace:
#0 /home/.../apache.....sk/classes/datarenderer.class.php(1274): Datarenderer->renderWorkersBar(Array, 'localhost', 'px')
#1 /home/.../apache.....sk/classes/datarenderer.class.php(1342): Datarenderer->_getWorkersData(Array, true, 175)
#2 /home/.../apache.....sk/views/serverinfos.php(11): Datarenderer->renderGroupAndServers(Array)
#3 /home/.../apache.....sk/index.php(83): include('/home/.../apa...')
#4 {main}
 thrown in /home/.../apache.....sk/classes/datarenderer.class.php on line 1454
```

**Comment by axelhahn** [comment]
Hi @azurit 

thanks for reporting this! 
I see where the division by zero occurs. I can fix that.

But I would like to know in which constellation it happens.
the file ./config/config_servers.json ... what does it contain? If you just initialized it there should be only localhost - something like that:
```txt
{
    "default": {
        "servers": {
            "localhost": {
                "label": "localhost"
            }
        }
    }
}
```
If so - what is the response of `curl -i localhost/server-status`?

Kind regards,
Axel

**Comment by azurit** [comment]
Yes, that file contains exact data as you wrote.

Result is our custom default page (there is no mod_status set on `/server-status` URI, is that a requirement?):
```
# curl -i localhost/server-status
HTTP/1.1 200 OK
Date: Tue, 28 Nov 2023 21:10:32 GMT
Server: RANDOM
Vary: Accept-Encoding
Cache-Control: no-cache, no-store, max-age=0
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
        html {height: 100%; width: 100%; border: 0; margin: 0}
        body {height: 100%; width: 100%; border: 0; margin: 0}
        iframe {height: 100%; width: 100%; border: 0; margin: 0}
        div {height: 100%; width: 100%; border: 0; margin: 0}
</style>
</head>
<body>
<div><iframe src="https://<censored>/pages/1//"></iframe></div>
</body>
</html>
```

**Comment by axelhahn** [comment]
Thanks for your http response!

On a system to be monitored you need the module mod_status and the setting ExtendedStatus On.
https://www.axel-hahn.de/docs/apachestatus/get_started.htm#Onmonitoredsystems

(1)
I fixed the division by 0 in the linked branch in the datarenderer.class.php
https://github.com/axelhahn/pimped-apache-status/blob/475d22e58dbc0a85ae5d9f528065a92c29c77417/classes/datarenderer.class.php#L1446

(2)
On the system where the apache status is installed I add "localhost" by default. If you would install mod_status and add ExtendedStatus On then it would run without applying the datarenderer.class.php.

(3)
If you try to add other hosts to monitor the response will be checked if it is a server status response. I need to verify it for localhost too. If it is done I will merge it into master and make a new release.

Kind regards,
Axel

**Comment by azurit** [comment]
It works, thank you!
