### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by darthjuanan** [axelhahn/pimped-apache-status#5]
Hi!

First, thanks for your great job. It's amazing!

But I have a problem with my installation.

I've installed it on /opt/apaches folder, but the URL is http://IP/apaches (is an "Alias" tag in the apache configuration).

So all the links are changed to http://IP/opt/apaches/.... becouse the file get the __DIR__ value.

I've changed in the inc_config.php. I forced in this way:

> //$sSelfURL=str_replace('\\','/',str_replace(realpath($_SERVER['DOCUMENT_ROOT']), '', __DIR__));
> $sSelfURL='/apaches';

But, it's possible a value for URL in next versions?

Thanks in advance.

**Comment by axelhahn** [comment]
Hi darthjuanan,

thanks for your hint. So far the installation nor documentation described the usage of the tool with an alias. The idea was to place it below a webroot.

But I had a look: it doesn't seem to be difficult to support aliases with adding a config value. The default can be _false_ for the current behavior - if you set a value, this will be uses as $sSelfURL (like your example). This I can add in the next version that you do not need to patch the inc_config on every update.

I will inform you here.

I need to think about the process on a fresh installation. But this I could add in a later version.

regards,
Axel

**Comment by axelhahn** [comment]
Hi darthjuanan,

I just published an update. If you updated your own installation then you can use a new config variable which is visible in the settings too.
In the file ./config/config_user.json (this file is safe on update processes) add an entry 
`"selfurl": "/apaches"`
(with starting slash and no trailing slash).

Please leave a comment if it was working or not.

Kind regards,
Axel

**Comment by axelhahn** [comment]
see #24 ... the variable `$selfurl` can be removed in the next version.

**Comment by axelhahn** [comment]
it is done with https://github.com/axelhahn/pimped-apache-status/commit/883c8253aefce3708e2e689c85cdb61d0e550590#diff-ceefa11783c184687f67cca61c026a1e1eca03cfcb4f02a64627fb9083044690
